### ISSUE TITLE
[RESOLVED] Bluetooth joy buttons mapping different from wired mapping

### ISSUE THREAD

**Issue by jesusramondovale** [ros2/teleop_twist_joy#40]
Hey. I've got a Xbox Series X wireless controller. I launch the teleop_twist_node (and joy node automatically from inside) 

· Using the USB cable: 
    /joy topic is published perfectly
    /cmd_vel is published perfectly

· Unplug the cable and using bluetooth: 
    /joy topic is still published perfectly
    /cmd_vel is not published anymore

Do you know what's going on? It doesn't make any sense

**Comment by clalancette** [comment]
> · Unplug the cable and using bluetooth: /joy topic is still published perfectly /cmd_vel is not published anymore

It's been a long time since I played around with it, but my recollection was that over bluetooth the axis and button mappings might be different from when it is plugged in.  It is worthwhile to watch the `/joy` topic (`ros2 topic echo /joy`), and then press the various buttons and axes, both when it is plugged in and wireless.  See if they give the same results.  If they don't, then you'll need to pass different parameters for the axes when you are on bluetooth.

**Comment by jesusramondovale** [comment]
Yes, it was that. 

Exactly: when connected via bluetooth, the /joy message contains 4 buttons more on the mapping (can't use them, they aren't related to any physical button, don't know for what they are), so the no. 2 mapped button (physical 'X' button on the controller) becomes "empty" and unused. 

So if you got the enable button of the teleop_joy config setted on one of those buttons, /cmd_vel is no more published.

I'll close the thread. Thank you
